### ISSUE TITLE
Sort EndpointIds by AZ to enable resource composability 

### ISSUE THREAD

**Issue by x6j8x** [aws-cloudformation/aws-cloudformation-resource-providers-networkfirewall#15]
Hi,

currently it is not possible to instantiate a working, self-contained, multi-AZ CloudFormation stack containing a AWS::NetworkFirewall::Firewall resource. 

The main reason is the current behaviour that the `EndpointIds` attribute does not guarantee any particular order. This makes it impossible to create the AWS::EC2::Route resources necessary to ensure that traffic from (or to) the workload subnets actually traverses the Firewall (without resorting to "shell-script" CustomResource Lambdas as workaround). 

It would be a great improvement if the `EndpointIds` would return its entries at least in "natural" AZ order (a-z). 

This way the user would be enabled to actually pick the necessary entries from the list with standard CloudFormation intrinsic functions (`Fn::Split`, `Fn::Select`). The format of `AZ:EndpointId` can stay the same as it can be easily deconstructed using the same functions. 

As a result users would be able to create self-contained CloudFormation stacks with _working routing_ and without using CustomResource Lambdas. 

Best,

Sascha

**Comment by Dunmail** [comment]
+1

**Comment by adamspicer** [comment]
+1
See workaround lambda here: https://github.com/aws-samples/aws-networkfirewall-cfn-templates/blob/main/distributed_architecture/anfw-distributed-2az-template.yaml

**Comment by Wittionary** [comment]
@yiweiy-aws How can we make headway on this issue?

**Comment by kallu** [comment]
I would very much like to see either ordered list or even option to use attribute to select the endpoint for given AZ. While waiting that, you actually can pick endpoint from the list for given AZ using combination of Splits and Joins. It doesn't look pretty but works. Below is an example how to pick FW endpoint for AZ-A to setup default route though FW.

```
 InspectionTGWRouteA:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref InspectionTGWRouteTableA
      DestinationCidrBlock: '0.0.0.0/0'
      VpcEndpointId: !Select [ 0, !Split [ ',', !Select [ 1 , !Split [ 'a:', !Join [ ',', !GetAtt NetworkFW.EndpointIds ] ] ] ] ]
```
